from PyQt5 import QtCore
from PyQt5.QtWidgets import QDialog, QGridLayout, QLabel, QSpinBox, QLineEdit, QCheckBox, QDoubleSpinBox, QDialogButtonBox


class CompactBarPopup(QDialog):

    def __init__(self, parent=None, vars=None, **kw):
        super(CompactBarPopup, self).__init__(parent)
        self.setWindowTitle("Compact Bar Plot")
        grid = QGridLayout()
        grid.setAlignment(QtCore.Qt.AlignTop)
        self.setLayout(grid)
        self.vars = vars["compact_bar_settings"]

        bar_cols_label = QLabel("Columns Per Page", self)
        bar_rows_label = QLabel("Rows Per Page", self)
        apply_status_label = QLabel("Apply Status?", self)
        meas_bar_colour_label = QLabel("Measured Bar Colour", self)
        lost_bar_colour_label = QLabel("Missing Bar Colour", self)
        unassigned_bar_colour_label = QLabel("Unassigned Bar Colour", self)
        bar_width_label = QLabel("Bar Width", self)
        bar_alpha_label = QLabel("Bar Alpha", self)
        bar_linewidth = QLabel("Bar Line Width", self)
        bar_title_y_label = QLabel("Title Y", self)
        bar_font_size_label = QLabel("Title Font Size", self)
        bar_font_label = QLabel("Title Font", self)
        bar_threshold_label = QLabel("Bar Threshold", self)
        bar_threshold_colour_label = QLabel("Bar Threshold Colour", self)
        bar_threshold_colour_lw_label = QLabel("Bar Threshold Line Width", self)
        bar_x_label_font_label = QLabel("X Label Font", self)
        bar_x_label_font_size_label = QLabel("X Label Font Size", self)
        bar_x_label_padding_label = QLabel("X Label Padding", self)
        bar_x_label_weight_label = QLabel("X Font Weight Padding", self)


        x_tick_rotation_label = QLabel("X Tick Rotation", self)
        x_tick_font_label = QLabel("X Tick Font", self)
        x_tick_font_size_label = QLabel("X Tick Font Size", self)
        x_tick_padding_label = QLabel("X Tick Padding", self)

        bar_y_label_font_label = QLabel("Y Label Font", self)
        bar_y_label_font_size_label = QLabel("Y Label Font Size", self)
        bar_y_label_padding_label = QLabel("Y Label Padding", self)
        bar_y_label_weight_label = QLabel("Y Font Weight", self)

        y_tick_font_size_label = QLabel("Y Tick Font Size", self)
        y_tick_padding_label = QLabel("Y Tick Padding", self)
        bar_y_tick_length_label = QLabel("Y Tick Length", self)
        y_grid_colour_label = QLabel("Y Grid Colour", self)
        mark_prolines_label = QLabel("Mark Prolines", self)
        proline_marker_label = QLabel("Proline Marker", self)
        user_details_label = QLabel("Mark User Details", self)
        mark_size_label = QLabel("Mark Font Size", self)
        shade_unassigned_label = QLabel("Shade Unassigned", self)
        unassigned_shade_colour_label = QLabel("Unassigned Shade Colour", self)
        unassigned_shade_alpha_label = QLabel("Unassigned Shade Alpha", self)

        self.layout().addWidget(bar_cols_label, 0, 0)
        self.layout().addWidget(bar_rows_label, 1, 0)
        self.layout().addWidget(apply_status_label, 2, 0)
        self.layout().addWidget(meas_bar_colour_label, 3, 0)
        self.layout().addWidget(lost_bar_colour_label, 4, 0)
        self.layout().addWidget(unassigned_bar_colour_label, 5, 0)
        self.layout().addWidget(bar_width_label, 6, 0)
        self.layout().addWidget(bar_alpha_label, 7, 0)
        self.layout().addWidget(bar_linewidth, 8, 0)
        self.layout().addWidget(bar_title_y_label, 9, 0)
        self.layout().addWidget(bar_font_size_label, 10, 0)
        self.layout().addWidget(bar_font_label, 11, 0)
        self.layout().addWidget(bar_threshold_label, 12, 0)
        self.layout().addWidget(bar_threshold_colour_label, 13, 0)
        self.layout().addWidget(bar_threshold_colour_lw_label, 14, 0)

        self.layout().addWidget(bar_x_label_font_label, 15, 0)
        self.layout().addWidget(bar_x_label_font_size_label, 16, 0)
        self.layout().addWidget(bar_x_label_padding_label, 17, 0)
        self.layout().addWidget(bar_x_label_weight_label, 18, 0)


        self.layout().addWidget(x_tick_rotation_label, 0, 2)
        self.layout().addWidget(x_tick_font_label, 1, 2)
        self.layout().addWidget(x_tick_font_size_label, 2, 2)
        self.layout().addWidget(x_tick_padding_label, 3, 2)

        self.layout().addWidget(bar_y_label_font_label, 4, 2)
        self.layout().addWidget(bar_y_label_font_size_label, 5, 2)
        self.layout().addWidget(bar_y_label_padding_label, 6, 2)
        self.layout().addWidget(bar_y_label_weight_label, 7, 2)
        self.layout().addWidget(bar_y_tick_length_label, 8, 2)



        self.layout().addWidget(y_tick_font_size_label, 9, 2)
        self.layout().addWidget(y_tick_padding_label, 10, 2)
        self.layout().addWidget(y_grid_colour_label, 11, 2)
        self.layout().addWidget(mark_prolines_label, 12, 2)
        self.layout().addWidget(proline_marker_label, 13, 2)
        self.layout().addWidget(user_details_label, 14, 2)
        self.layout().addWidget(mark_size_label, 15, 2)
        self.layout().addWidget(shade_unassigned_label, 16, 2)
        self.layout().addWidget(unassigned_shade_colour_label, 17, 2)
        self.layout().addWidget(unassigned_shade_alpha_label, 18, 2)

        self.bar_cols = QSpinBox()
        self.bar_rows = QSpinBox()
        self.apply_status = QCheckBox()
        self.meas_bar_colour = QLineEdit()
        self.lost_bar_colour = QLineEdit()
        self.unassigned_bar_colour = QLineEdit()
        self.bar_width = QDoubleSpinBox()
        self.bar_alpha = QSpinBox()
        self.bar_linewidth = QDoubleSpinBox()
        self.bar_title_y = QDoubleSpinBox()
        self.bar_font_size = QSpinBox()
        self.title_font = QLineEdit()
        self.title_font_size = QSpinBox()
        self.bar_threshold = QCheckBox()
        self.bar_threshold_colour = QLineEdit()
        self.bar_threshold_linewidth = QSpinBox()
        self.bar_x_label_font = QLineEdit()
        self.bar_x_label_font_size = QSpinBox()
        self.bar_x_label_padding = QDoubleSpinBox()
        self.bar_x_label_weight = QLineEdit()

        self.x_tick_rotation = QSpinBox()
        self.x_tick_font_size = QSpinBox()
        self.x_tick_font = QLineEdit()
        self.x_tick_padding = QDoubleSpinBox()

        self.bar_y_label_font = QLineEdit()
        self.bar_y_label_font_size = QSpinBox()
        self.bar_y_label_padding = QDoubleSpinBox()
        self.bar_y_label_weight = QLineEdit()
        self.y_tick_font = QLineEdit()
        self.y_tick_font_size = QSpinBox()
        self.y_tick_rotation = QSpinBox()
        self.y_tick_padding = QDoubleSpinBox()
        self.y_tick_length = QSpinBox()
        self.y_grid_colour = QLineEdit()
        self.markProlines = QCheckBox()
        self.proline_marker = QLineEdit()
        self.user_details = QCheckBox()
        self.mark_font_size = QSpinBox()
        self.shade_unassigned = QCheckBox()
        self.unassigned_shade_colour = QLineEdit()
        self.unassigned_shade_alpha = QDoubleSpinBox()

        self.layout().addWidget(self.bar_cols, 0, 1)
        self.layout().addWidget(self.bar_rows, 1, 1)
        self.layout().addWidget(self.apply_status, 2, 1)
        self.layout().addWidget(self.meas_bar_colour, 3, 1)
        self.layout().addWidget(self.lost_bar_colour, 4, 1)
        self.layout().addWidget(self.unassigned_bar_colour, 5, 1)
        self.layout().addWidget(self.bar_width, 6, 1)
        self.layout().addWidget(self.bar_alpha, 7, 1)
        self.layout().addWidget(self.bar_linewidth, 8, 1)
        self.layout().addWidget(self.bar_title_y, 9, 1)
        self.layout().addWidget(self.bar_font_size, 10, 1)
        self.layout().addWidget(self.title_font, 11, 1)
        self.layout().addWidget(self.bar_threshold, 12, 1)
        self.layout().addWidget(self.bar_threshold_colour, 13, 1)
        self.layout().addWidget(self.bar_threshold_linewidth, 14, 1)

        self.layout().addWidget(self.bar_x_label_font, 15, 1)
        self.layout().addWidget(self.bar_x_label_font_size, 16, 1)
        self.layout().addWidget(self.bar_x_label_padding, 17, 1)
        self.layout().addWidget(self.bar_x_label_weight, 18, 1)


        self.layout().addWidget(self.x_tick_rotation, 0, 3)
        self.layout().addWidget(self.x_tick_font_size, 1, 3)
        self.layout().addWidget(self.x_tick_font, 2, 3)
        self.layout().addWidget(self.x_tick_padding, 3, 3)

        self.layout().addWidget(self.bar_y_label_font, 4, 3)
        self.layout().addWidget(self.bar_y_label_font_size, 5, 3)
        self.layout().addWidget(self.bar_y_label_padding, 6, 3)
        self.layout().addWidget(self.bar_y_label_weight, 7, 3)


        self.layout().addWidget(self.y_tick_length, 8, 3)
        self.layout().addWidget(self.y_tick_font_size, 9, 3)
        self.layout().addWidget(self.y_tick_padding, 10, 3)
        self.layout().addWidget(self.y_grid_colour, 11, 3)
        self.layout().addWidget(self.markProlines, 12, 3)
        self.layout().addWidget(self.proline_marker, 13, 3)
        self.layout().addWidget(self.user_details, 14, 3)
        self.layout().addWidget(self.mark_font_size, 15, 3)
        self.layout().addWidget(self.shade_unassigned, 16, 3)
        self.layout().addWidget(self.unassigned_shade_colour, 17, 3)
        self.layout().addWidget(self.unassigned_shade_alpha, 18, 3)

        self.buttonBox = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel | QDialogButtonBox.RestoreDefaults)

        self.buttonBox.accepted.connect(self.setValues)
        self.buttonBox.rejected.connect(self.reject)
        self.buttonBox.button(QDialogButtonBox.RestoreDefaults).clicked.connect(self.set_defaults)

        self.layout().addWidget(self.buttonBox, 29, 2, 1, 2)

        # self.set_defaults()

    def set_defaults(self):
        self.bar_cols.setValue(3)
        self.bar_rows.setValue(5)
        self.apply_status.setChecked(True)
        self.meas_bar_colour.setText('k')
        self.lost_bar_colour.setText('red')
        self.unassigned_bar_colour.setText('grey')
        self.bar_width.setValue(0.7)
        self.bar_alpha.setValue(1)
        self.bar_linewidth.setValue(0)
        self.bar_title_y.setValue(1.01)
        self.title_font.setText('Arial')
        self.title_font_size.setValue(8)
        self.bar_threshold.setChecked(True)
        self.bar_threshold_colour.setText('red')
        self.bar_threshold_linewidth.setValue(1)
        self.x_tick_rotation.setValue(90)
        self.x_tick_font_size.setValue(6)
        self.x_tick_font.setText('Arial')
        self.x_tick_padding.setValue(1.0)
        self.y_tick_font_size.setValue(9)
        self.y_tick_padding.setValue(-3.0)
        self.y_grid_colour.setText('grey')
        self.markProlines.setChecked(True)
        self.proline_marker.setText('P')
        self.user_details.setChecked(True)
        self.mark_font_size.setValue(3)
        self.shade_unassigned.setChecked(True)
        self.unassigned_shade_colour.setText('grey')
        self.unassigned_shade_alpha.setValue(0.5)

    def setValues(self):
        self.vars["do_comp_bar"] = True
        self.vars["comp_bar_cols_page"] =  self.bar_cols.value()
        self.vars["comp_bar_rows_page"] = self.bar_rows.value()
        self.vars["comp_bar_color_measured"] = self.meas_bar_colour.text()
        self.vars["comp_bar_apply_status_2_bar_color"] = self.apply_status.isChecked()
        self.vars["comp_bar_color_lost"] = self.lost_bar_colour.text()
        self.vars["comp_bar_color_unassigned"] = self.unassigned_bar_colour.text()
        self.vars["comp_bar_bar_width"] = self.bar_width.value()
        self.vars["comp_bar_bar_alpha"] = self.bar_alpha.value()
        self.vars["comp_bar_bar_linewidth"] = self.bar_linewidth.value()
        self.vars["comp_bar_title_y"] = self.bar_title_y.value()
        self.vars["comp_bar_title_fn"] = self.title_font.text()
        self.vars["comp_bar_title_fs"] = self.title_font_size.value()
        self.vars["comp_bar_plot_threshold"] = self.bar_threshold.isChecked()
        self.vars["comp_bar_plot_threshold_color"] = self.bar_threshold_colour.text()
        self.vars["comp_bar_plot_threshold_lw"] = self.bar_threshold_linewidth.value()
        self.vars["comp_bar_x_label_fn"] = self.bar_x_label_font.text()
        self.vars["comp_bar_x_label_fs"] = self.bar_x_label_font_size.value()
        self.vars["comp_bar_x_label_pad"] = self.bar_x_label_padding.value()
        self.vars["comp_bar_x_label_weight"] = self.bar_x_label_weight.text()
        self.vars["comp_bar_x_ticks_fn"] = self.x_tick_font.text()
        self.vars["comp_bar_x_ticks_fs"] = self.x_tick_font_size.value()
        self.vars["comp_bar_x_ticks_rot"] = self.x_tick_rotation.value()
        self.vars["comp_bar_x_ticks_pad"] = self.x_tick_padding.value()
        self.vars["comp_bar_y_label_fn"] = self.bar_y_label_font.text()
        self.vars["comp_bar_y_label_weight"] = self.bar_y_label_weight.text()
        self.vars["comp_bar_y_label_fs"] = self.bar_y_label_font_size.value()
        self.vars["comp_bar_y_label_pad"] = self.bar_y_label_padding.value()
        self.vars["comp_bar_y_ticks_fs"] = self.y_tick_font_size.value()
        self.vars["comp_bar_y_ticks_pad"] = self.y_tick_padding.value()
        self.vars["comp_bar_y_ticks_len"] = self.y_tick_length.value()
        self.vars["comp_bar_y_grid_color"] = self.y_grid_colour.text()
        self.vars["comp_bar_mark_prolines"] = self.markProlines.isChecked()
        self.vars["comp_bar_proline_mark"] = self.proline_marker.text()
        self.vars["comp_bar_mark_user_details"] = self.user_details.isChecked()
        self.vars["comp_bar_mark_fs"] = self.mark_font_size.value()
        self.vars["comp_bar_unassigned_shade"] = self.shade_unassigned.isChecked()
        self.vars["comp_bar_unassigned_shade_color"] = self.unassigned_shade_colour.text()
        self.vars["comp_bar_unassigned_shade_alpha"] = self.unassigned_shade_alpha.value()
        self.accept()
