from PyQt5 import QtCore
from PyQt5.QtWidgets import QDialog, QGridLayout, QLabel, QSpinBox, QLineEdit, QCheckBox, QDoubleSpinBox, QDialogButtonBox


class ExtendedBarPopup(QDialog):

    def __init__(self, parent=None, **kw):
        super(ExtendedBarPopup, self).__init__(parent)
        self.setWindowTitle("Extended Bar Plot")
        grid = QGridLayout()
        grid.setAlignment(QtCore.Qt.AlignTop)
        self.setLayout(grid)

        bar_cols_label = QLabel("Columns Per Page", self)
        bar_rows_label = QLabel("Rows Per Page", self)
        apply_status_label = QLabel("Apply Status?", self)
        meas_bar_colour_label = QLabel("Measured Bar Colour", self)
        lost_bar_colour_label = QLabel("Missing Bar Colour", self)
        unassigned_bar_colour_label = QLabel("Unassigned Bar Colour", self)
        bar_width_label = QLabel("Bar Width", self)
        bar_alpha_label = QLabel("Bar Alpha", self)
        bar_linewidth = QLabel("Bar Line Width", self)
        bar_title_y_label = QLabel("Title Y", self)
        bar_font_size_label = QLabel("Title Font Size", self)
        bar_font_label = QLabel("Title Font", self)
        bar_threshold_label = QLabel("Bar Threshold", self)
        bar_threshold_colour_label = QLabel("Bar Threshold Colour", self)
        bar_threshold_colour_lw_label = QLabel("Bar Threshold Line Width", self)
        x_tick_rotation_label = QLabel("X Tick Rotation", self)
        x_tick_font_label = QLabel("X Tick Font", self)
        x_tick_font_size_label = QLabel("X Tick Font Size", self)
        x_tick_padding_label = QLabel("X Tick Padding", self)
        y_tick_font_size_label = QLabel("Y Tick Font Size", self)
        y_grid_colour_label = QLabel("Y Grid Colour", self)
        mark_prolines_label = QLabel("Mark Prolines", self)
        proline_marker_label = QLabel("Proline Marker", self)
        user_details_label = QLabel("Mark User Details", self)

        self.layout().addWidget(bar_cols_label, 0, 0)
        self.layout().addWidget(bar_rows_label, 1, 0)
        self.layout().addWidget(apply_status_label, 2, 0)
        self.layout().addWidget(meas_bar_colour_label, 3, 0)
        self.layout().addWidget(lost_bar_colour_label, 4, 0)
        self.layout().addWidget(unassigned_bar_colour_label, 5, 0)
        self.layout().addWidget(bar_width_label, 6, 0)
        self.layout().addWidget(bar_alpha_label, 7, 0)
        self.layout().addWidget(bar_linewidth, 8, 0)
        self.layout().addWidget(bar_title_y_label, 9, 0)
        self.layout().addWidget(bar_font_size_label, 10, 0)
        self.layout().addWidget(bar_font_label, 11, 0)
        self.layout().addWidget(bar_threshold_label, 12, 0)
        self.layout().addWidget(bar_threshold_colour_label, 13, 0)
        self.layout().addWidget(bar_threshold_colour_lw_label, 14, 0)
        self.layout().addWidget(x_tick_rotation_label, 15, 0)
        self.layout().addWidget(x_tick_font_label, 16, 0)
        self.layout().addWidget(x_tick_font_size_label, 17, 0)
        self.layout().addWidget(x_tick_padding_label, 18, 0)
        self.layout().addWidget(y_tick_font_size_label, 19, 0)
        self.layout().addWidget(y_grid_colour_label, 20, 0)
        self.layout().addWidget(mark_prolines_label, 21, 0)
        self.layout().addWidget(proline_marker_label, 22, 0)
        self.layout().addWidget(user_details_label, 23, 0)

        self.bar_cols = QSpinBox()
        self.bar_rows = QSpinBox()
        self.apply_status = QCheckBox()
        self.meas_bar_colour = QLineEdit()
        self.lost_bar_colour = QLineEdit()
        self.unassigned_bar_colour = QLineEdit()
        self.bar_width = QDoubleSpinBox()
        self.bar_alpha = QSpinBox()
        self.bar_linewidth = QDoubleSpinBox()
        self.bar_title_y = QDoubleSpinBox()
        self.bar_title_font = QLineEdit()
        self.bar_title_font_size = QSpinBox()
        self.bar_threshold = QCheckBox()
        self.bar_threshold_colour = QLineEdit()
        self.bar_threshold_linewidth = QSpinBox()
        self.x_tick_rotation = QSpinBox()
        self.x_tick_font_size = QSpinBox()
        self.x_tick_font = QLineEdit()
        self.x_tick_padding = QDoubleSpinBox()
        self.y_tick_font_size = QSpinBox()
        self.y_grid_colour = QLineEdit()
        self.markProlines = QCheckBox()
        self.proline_marker = QLineEdit()
        self.user_details = QCheckBox()

        self.layout().addWidget(self.bar_cols, 0, 1)
        self.layout().addWidget(self.bar_rows, 1, 1)
        self.layout().addWidget(self.apply_status, 2, 1)
        self.layout().addWidget(self.meas_bar_colour, 3, 1)
        self.layout().addWidget(self.lost_bar_colour, 4, 1)
        self.layout().addWidget(self.unassigned_bar_colour, 5, 1)
        self.layout().addWidget(self.bar_width, 6, 1)
        self.layout().addWidget(self.bar_alpha, 7, 1)
        self.layout().addWidget(self.bar_linewidth, 8, 1)
        self.layout().addWidget(self.bar_title_y, 9, 1)
        self.layout().addWidget(self.bar_title_font_size, 10, 1)
        self.layout().addWidget(self.bar_title_font, 11, 1)
        self.layout().addWidget(self.bar_threshold, 12, 1)
        self.layout().addWidget(self.bar_threshold_colour, 13, 1)
        self.layout().addWidget(self.bar_threshold_linewidth, 14, 1)
        self.layout().addWidget(self.x_tick_rotation, 15, 1)
        self.layout().addWidget(self.x_tick_font_size, 16, 1)
        self.layout().addWidget(self.x_tick_font, 17, 1)
        self.layout().addWidget(self.x_tick_padding, 18, 1)
        self.layout().addWidget(self.y_tick_font_size, 19, 1)
        self.layout().addWidget(self.y_grid_colour, 20, 1)
        self.layout().addWidget(self.markProlines, 21, 1)
        self.layout().addWidget(self.proline_marker, 22, 1)
        self.layout().addWidget(self.user_details, 23, 1)

        self.buttonBox = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel | QDialogButtonBox.RestoreDefaults)

        self.buttonBox.accepted.connect(self.setValues)
        self.buttonBox.rejected.connect(self.reject)
        self.buttonBox.button(QDialogButtonBox.RestoreDefaults).clicked.connect(self.set_defaults)

        self.layout().addWidget(self.buttonBox, 24, 0, 1, 2)

        # self.set_defaults()

    def set_defaults(self):
        self.bar_cols.setValue(1)
        self.bar_rows.setValue(6)
        self.apply_status.setChecked(True)
        self.meas_bar_colour.setText('k')
        self.lost_bar_colour.setText('red')
        self.unassigned_bar_colour.setText('grey')
        self.bar_width.setValue(0.7)
        self.bar_alpha.setValue(1)
        self.bar_linewidth.setValue(10)
        self.bar_title_y.setValue(1.05)
        self.bar_title_font.setText('Arial')
        self.bar_title_font_size.setValue(10)
        self.bar_threshold.setChecked(True)
        self.bar_threshold_colour.setText('red')
        self.bar_threshold_linewidth.setValue(1)
        self.x_tick_rotation.setValue(90)
        self.x_tick_font_size.setValue(6)
        self.x_tick_font.setText('monospace')
        self.x_tick_padding.setValue(0.1)
        self.y_tick_font_size.setValue(9)
        self.y_grid_colour.setText('grey')
        self.markProlines.setChecked(True)
        self.proline_marker.setText('P')
        self.user_details.setChecked(True)

    def setValues(self):
        self.accept()
