from PyQt5 import QtCore
from PyQt5.QtWidgets import QDialog, QGridLayout, QLabel, QSpinBox, QLineEdit, QCheckBox, QDoubleSpinBox, QDialogButtonBox


class ResidueEvolutionPopup(QDialog):

    def __init__(self, parent=None, **kw):
        super(ResidueEvolutionPopup, self).__init__(parent)
        self.setWindowTitle("Residue Evolution Plot")
        grid = QGridLayout()
        grid.setAlignment(QtCore.Qt.AlignTop)
        self.setLayout(grid)

        res_evo_cols_label = QLabel("Columns Per Page", self)
        res_evo_rows_label = QLabel("Rows Per Page", self)
        res_evo_title_y_label = QLabel("Title Y", self)
        res_evo_font_size_label = QLabel("Title Font Size", self)
        res_evo_font_label = QLabel("Title Font", self)
        set_x_values_label = QLabel("Set X Values", self)
        x_tick_font_size_label = QLabel("X Tick Font Size", self)
        x_tick_padding_label = QLabel("X Tick Padding", self)
        x_tick_flag_label = QLabel("Label X Axis?", self)
        y_tick_padding_label = QLabel("Y Tick Padding", self)
        y_tick_font_size_label = QLabel("Y Tick Font Size", self)
        res_evo_plot_colour_label = QLabel("Plot Colour", self)
        res_evo_plot_line_style_label = QLabel("Line Style", self)
        res_evo_plot_marker_style_label = QLabel("Marker Style", self)
        res_evo_plot_marker_colour_label = QLabel("Marker Colour", self)
        res_evo_plot_marker_size_label = QLabel("Marker Size", self)
        res_evo_plot_line_width_label = QLabel("Line Width", self)
        res_evo_plot_fill_between_label = QLabel("Fill Between?", self)
        res_evo_plot_fill_colour_label = QLabel("Fill Colour", self)
        res_evo_plot_fill_alpha_label = QLabel("Fill Alpha", self)

        self.layout().addWidget(res_evo_cols_label, 0, 0)
        self.layout().addWidget(res_evo_rows_label, 1, 0)
        self.layout().addWidget(res_evo_title_y_label, 2, 0)
        self.layout().addWidget(res_evo_font_size_label, 3, 0)
        self.layout().addWidget(res_evo_font_label, 4, 0)
        self.layout().addWidget(set_x_values_label, 5, 0)
        self.layout().addWidget(x_tick_font_size_label, 6, 0)
        self.layout().addWidget(x_tick_padding_label, 7, 0)
        self.layout().addWidget(x_tick_flag_label, 8, 0)
        self.layout().addWidget(y_tick_padding_label, 9, 0)
        self.layout().addWidget(y_tick_font_size_label, 10, 0)
        self.layout().addWidget(res_evo_plot_colour_label, 11, 0)
        self.layout().addWidget(res_evo_plot_line_style_label, 12, 0)
        self.layout().addWidget(res_evo_plot_marker_style_label, 13, 0)
        self.layout().addWidget(res_evo_plot_marker_colour_label, 14, 0)
        self.layout().addWidget(res_evo_plot_marker_size_label, 15, 0)
        self.layout().addWidget(res_evo_plot_line_width_label, 16, 0)
        self.layout().addWidget(res_evo_plot_fill_between_label, 17, 0)
        self.layout().addWidget(res_evo_plot_fill_colour_label, 18, 0)
        self.layout().addWidget(res_evo_plot_fill_alpha_label, 19, 0)



        self.res_evo_cols = QSpinBox()
        self.res_evo_rows = QSpinBox()
        self.res_evo_title_y = QDoubleSpinBox()
        self.res_evo_font_size = QSpinBox()
        self.res_evo_font = QLineEdit()
        self.set_x_values = QCheckBox()
        self.x_tick_font_size = QSpinBox()
        self.x_tick_padding = QDoubleSpinBox()
        self.x_label_flag = QCheckBox()
        self.y_tick_padding = QDoubleSpinBox()
        self.y_tick_font_size = QSpinBox()
        self.res_evo_plot_colour = QLineEdit()
        self.res_evo_plot_line_style = QLineEdit()
        self.res_evo_plot_marker_style = QLineEdit()
        self.res_evo_plot_marker_colour = QLineEdit()
        self.res_evo_plot_marker_size = QSpinBox()
        self.res_evo_plot_line_width = QSpinBox()
        self.res_evo_plot_fill_between = QCheckBox()
        self.res_evo_plot_fill_colour = QLineEdit()
        self.res_evo_fill_alpha = QDoubleSpinBox()


        self.layout().addWidget(self.res_evo_cols, 0, 1)
        self.layout().addWidget(self.res_evo_rows, 1, 1)
        self.layout().addWidget(self.res_evo_title_y, 2, 1)
        self.layout().addWidget(self.res_evo_font_size, 3, 1)
        self.layout().addWidget(self.res_evo_font, 4, 1)
        self.layout().addWidget(self.set_x_values, 5, 1)
        self.layout().addWidget(self.x_tick_font_size, 6, 1)
        self.layout().addWidget(self.x_tick_padding, 7, 1)
        self.layout().addWidget(self.x_label_flag, 8, 1)
        self.layout().addWidget(self.y_tick_padding, 9, 1)
        self.layout().addWidget(self.y_tick_font_size, 10, 1)
        self.layout().addWidget(self.res_evo_plot_colour, 11, 1)
        self.layout().addWidget(self.res_evo_plot_line_style, 12, 1)
        self.layout().addWidget(self.res_evo_plot_marker_style, 13, 1)
        self.layout().addWidget(self.res_evo_plot_marker_colour, 14, 1)
        self.layout().addWidget(self.res_evo_plot_marker_size, 15, 1)
        self.layout().addWidget(self.res_evo_plot_line_width, 16, 1)
        self.layout().addWidget(self.res_evo_plot_fill_between, 17, 1)
        self.layout().addWidget(self.res_evo_plot_fill_colour, 18, 1)
        self.layout().addWidget(self.res_evo_fill_alpha, 19, 1)


        self.buttonBox = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel | QDialogButtonBox.RestoreDefaults)

        self.buttonBox.accepted.connect(self.setValues)
        self.buttonBox.rejected.connect(self.reject)
        self.buttonBox.button(QDialogButtonBox.RestoreDefaults).clicked.connect(self.set_defaults)

        self.layout().addWidget(self.buttonBox, 20, 0, 1, 2)

        # self.set_defaults()

    def set_defaults(self):
        self.res_evo_cols.setValue(4)
        self.res_evo_rows.setValue(6)
        self.res_evo_title_y.setValue(0.97)
        self.res_evo_font_size.setValue(8)
        self.res_evo_font.setText('Arial')
        self.set_x_values.setChecked(True)
        self.x_tick_font_size.setValue(7)
        self.x_tick_padding.setValue(1.0)
        self.x_label_flag.setChecked(True)
        self.y_tick_padding.setValue(1)
        self.y_tick_font_size.setValue(7)
        self.res_evo_plot_colour.setText('r')
        self.res_evo_plot_line_style.setText('-')
        self.res_evo_plot_marker_style.setText('o')
        self.res_evo_plot_marker_colour.setText('darkred')
        self.res_evo_plot_marker_size.setValue(3)
        self.res_evo_plot_line_width.setValue(1)
        self.res_evo_plot_fill_between.setChecked(True)
        self.res_evo_plot_fill_colour.setText('pink')
        self.res_evo_fill_alpha.setValue(1.0)

    def setValues(self):
        self.accept()
